# Generated by Django 2.2 on 2019-04-28 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starship_class', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('length', models.FloatField(null=True)),
                ('hyperdrive_rating', models.FloatField(null=True)),
                ('cargo_capacity', models.BigIntegerField(null=True)),
                ('crew', models.IntegerField(null=True)),
                ('passengers', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ship_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='shiptrader.Starship')),
            ],
        ),
    ]
