#!/bin/sh

until PGPASSWORD=postgres psql --host postgresql --username postgres -c '\l' > /dev/null; do
  echo "Postgres is unavailable - sleeping"
  sleep 1
done

export PYTHONUNBUFFERED=0
./testsite/manage.py migrate
./testsite/manage.py runserver 0.0.0.0:8008
